### ISSUE TITLE
`BulkModulusWorkChain` is not compatible with `RelaxWorkChain` in aiida-vasp

### ISSUE THREAD

**Issue by lan496** [atztogo/aiida-vasp-bm#1]
`BulkModulusWorkChain` and `example/submit.py` do not seem to reflect the following two changes in `RelaxWorkChain` in aiida-vasp:
1. input parameters for relaxation are gathered in an input namespace, `relax`
https://github.com/aiida-vasp/aiida-vasp/commit/5e36317c92b04587aa185827eead314a2486fbdd#diff-ad6a501c3a7269b82ff59c5d11795452
2. A relaxed structure are stored at `self.outputs.relax.structure` not `self.outputs.relaxed_structure`
https://github.com/aiida-vasp/aiida-vasp/commit/1a2a55333570631931ba555605b34e762f0cc7d4

As to 2, nested outputs do not work currently ( https://github.com/aiida-vasp/aiida-vasp/issues/301
 ).
So, a relaxed structure can be accessed by `outputs['relax__structure']` for the present.

**Comment by atztogo** [comment]
I think we should discuss with aiida-vasp team. See https://github.com/aiida-vasp/aiida-vasp/issues/311.

**Comment by lan496** [comment]
Thank you for your reply.
I think it's better to update changes because the aiida-vasp tutorial instructs to install this repo.

**Comment by espenfl** [comment]
@atztogo @lan496 Thanks for pointing this out. Yes, please update accordingly. We have changed the structure of the workchains with respect to inputs and ouputs such that they now reside in namespaces. E.g. for the relaxation workchain, specific inputs related to that should now be put in e.g. `inputs.relax.someparameter` etc. Please have a look at the updated definition of the relaxation workchain: https://github.com/aiida-vasp/aiida-vasp/blob/develop/aiida_vasp/workchains/relax.py

Thanks for all the effort. That is greatly appreciated.
